/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package QKART_SANITY_LOGIN.Module1;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Arrays;
import java.util.List;
import java.util.Set;
import java.util.concurrent.TimeUnit;

import org.apache.commons.io.FileUtils;
import org.openqa.selenium.By;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.remote.BrowserType;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;

public class QkartSanity {

    public static String lastGeneratedUserName;


    public static RemoteWebDriver createDriver() throws MalformedURLException {
        // Launch Browser using Zalenium
        final DesiredCapabilities capabilities = new DesiredCapabilities();
        capabilities.setBrowserName(BrowserType.CHROME);
        RemoteWebDriver driver = new RemoteWebDriver(new URL("http://localhost:8082/wd/hub"), capabilities);
        return driver;
    }

    public static void logStatus(String type, String message, String status) {

        System.out.println(String.format("%s |  %s  |  %s | %s", String.valueOf(java.time.LocalDateTime.now()), type,
                message, status));
    }

    public static void takeScreenshot(WebDriver driver, String screenshotType, String description) {
        // TODO: CRIO_TASK_MODULE_SYNCHRONISATION - Implement method using below steps
        /*
         * 1. Check if the folder "/screenshots" exists, create if it doesn't
         * 2. Generate a unique string using the timestamp
         * 3. Capture screenshot
         * 4. Save the screenshot inside the "/screenshots" folder using the following
         * naming convention: screenshot_<Timestamp>_<ScreenshotType>_<Description>.png
         * eg: screenshot_2022-03-05T06:59:46.015489_StartTestcase_Testcase01.png
         */
        try {
            File dir = new File("./screenshots");
            if(!dir.exists()) {
                dir.mkdirs();
            }

            String timestamp = String.valueOf(java.time.LocalDateTime.now());
            String filename = String.format("screenshot_%s_%s_%s.png", timestamp, screenshotType, description);

            TakesScreenshot scrShot = ((TakesScreenshot)driver);
            File srcFile = scrShot.getScreenshotAs(OutputType.FILE);

            File destFile = new File("./screenshots/"+filename);
            FileUtils.copyFile(srcFile, destFile);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /*
     * Testcase01: Verify the functionality of Login button on the Home page
     */
    public static Boolean TestCase01(RemoteWebDriver driver) throws InterruptedException {
        Boolean status;
        takeScreenshot(driver,"Test Case 1 start","screenshot");
        logStatus("Start TestCase", "Test Case 1: Verify User Registration", "DONE");

        // Visit the Registration page and register a new user
        Register registration = new Register(driver);
        registration.navigateToRegisterPage();
        status = registration.registerUser("testUser", "abc@123", true);
        if (!status) {
            logStatus("End TestCase", "Test Case 1: Verify user Registration : ", status ? "PASS" : "FAIL");
            takeScreenshot(driver,"Test Case 1 fail","screenshot");
            // Return False as the test case Fails
            return false;
        } else {
            logStatus("TestCase 1", "Test Case Pass. User Registration Pass", "PASS");
        }

        // Save the last generated username
        lastGeneratedUserName = registration.lastGeneratedUsername;

        // Visit the login page and login with the previuosly registered user
        Login login = new Login(driver);
        login.navigateToLoginPage();
        status = login.PerformLogin(lastGeneratedUserName, "abc@123");
        logStatus("Test Step", "User Perform Login: ", status ? "PASS" : "FAIL");
        if (!status) {
            logStatus("End TestCase", "Test Case 1: Verify user Registration : ", status ? "PASS" : "FAIL");
            return false;
        }

        // Visit the home page and log out the logged in user
        Home home = new Home(driver);
        status = home.PerformLogout();
        logStatus("End TestCase", "Test Case 1: Verify user Registration : ", status ? "PASS" : "FAIL");
        takeScreenshot(driver,"Test Case 1 end","screenshot");
        return status;
    }

    /*
     * Verify that an existing user is not allowed to re-register on QKart
     */
    public static Boolean TestCase02(RemoteWebDriver driver) throws InterruptedException {
        Boolean status;
        takeScreenshot(driver,"Test Case 2 start","screenshot");
        logStatus("Start Testcase", "Test Case 2: Verify User Registration with an existing username ", "DONE");

        // Visit the Registration page and register a new user
        Register registration = new Register(driver);
        registration.navigateToRegisterPage();
        status = registration.registerUser("testUser", "abc@123", true);
        logStatus("Test Step", "User Registration : ", status ? "PASS" : "FAIL");
        if (!status) {
            logStatus("End TestCase", "Test Case 2: Verify user Registration : ", status ? "PASS" : "FAIL");
            takeScreenshot(driver,"Test Case 2 fail","screenshot");
            return false;
        }

        // Save the last generated username
        lastGeneratedUserName = registration.lastGeneratedUsername;

        // Visit the Registration page and try to register using the previously
        // registered user's credentials
        registration.navigateToRegisterPage();
        status = registration.registerUser(lastGeneratedUserName, "abc@123", false);

        // If status is true, then registration succeeded, else registration has
        // failed. In this case registration failure means Success
        logStatus("End TestCase", "Test Case 2: Verify user Registration : ", status ? "FAIL" : "PASS");
        takeScreenshot(driver,"Test Case 2 end","screenshot");
        return !status;
    }

    /*
     * Verify the functinality of the search text box
     */
    public static Boolean TestCase03(RemoteWebDriver driver) throws InterruptedException {
        takeScreenshot(driver,"Test Case 3 start","screenshot");
        logStatus("TestCase 3", "Start test case : Verify functionality of search box ", "DONE");
        boolean status;

        // Visit the home page
        Home homePage = new Home(driver);
        homePage.navigateToHome();

        // SLEEP_STMT_01 : Wait for Page to Load
        // Thread.sleep(5000);

        // Search for the "yonex" product
        status = homePage.searchForProduct("yonex");
        if (!status) {
            logStatus("TestCase 3", "Test Case Failure. Unable to search for given product", "FAIL");
            return false;
        }

        // Fetch the search results
        List<WebElement> searchResults = homePage.getSearchResults();

        // Verify the search results are available
        if (searchResults.size() == 0) {
            logStatus("TestCase 3", "Test Case Failure. There were no results for the given search string", "FAIL");
            takeScreenshot(driver,"Test Case 3 fail","screenshot");
            return false;
        }

        for (WebElement webElement : searchResults) {
            // Create a SearchResult object from the parent element
            SearchResult resultelement = new SearchResult(webElement);

            // Verify that all results contain the searched text
            String elementText = resultelement.getTitleofResult();
            if (!elementText.toUpperCase().contains("YONEX")) {
                logStatus("TestCase 3", "Test Case Failure. Test Results contains un-expected values: " + elementText,
                        "FAIL");
                return false;
            }
        }

        logStatus("Step Success", "Successfully validated the search results ", "PASS");
        // SLEEP_STMT_02
        // Thread.sleep(2000);

        // Search for product
        status = homePage.searchForProduct("Gesundheit");
        if (!status) {
            logStatus("TestCase 3", "Test Case Failure. Unable to search for given product", "FAIL");
            return false;
        }

        // Verify no search results are found
        searchResults = homePage.getSearchResults();
        if (searchResults.size() == 1) {
            if (homePage.isNoResultFound()) {
                logStatus("Step Success", "Successfully validated that no products found message is displayed", "PASS");
            }
            logStatus("TestCase 3", "Test Case PASS. Verified that no search results were found for the given text",
                    "PASS");
        } else {
            logStatus("TestCase 3", "Test Case Fail. Expected: no results , actual: Results were available", "FAIL");
            return false;
        }

        takeScreenshot(driver,"Test Case 3 end","screenshot");

        return true;
    }

    /*
     * Verify the presence of size chart and check if the size chart content is as
     * expected
     */
    public static Boolean TestCase04(RemoteWebDriver driver) throws InterruptedException {
        takeScreenshot(driver,"Test Case 4 start","screenshot");
        logStatus("TestCase 4", "Start test case : Verify the presence of size Chart", "DONE");
        boolean status = false;

        // Visit home page
        Home homePage = new Home(driver);
        homePage.navigateToHome();

        // SLEEP_STMT_03 : Wait for page to load
        // Thread.sleep(3000);

        // Search for product and get card content element of search results
        status = homePage.searchForProduct("Running Shoes");
        List<WebElement> searchResults = homePage.getSearchResults();

        // Create expected values
        List<String> expectedTableHeaders = Arrays.asList("Size", "UK/INDIA", "EU", "HEEL TO TOE");
        List<List<String>> expectedTableBody = Arrays.asList(Arrays.asList("6", "6", "40", "9.8"),
                Arrays.asList("7", "7", "41", "10.2"), Arrays.asList("8", "8", "42", "10.6"),
                Arrays.asList("9", "9", "43", "11"), Arrays.asList("10", "10", "44", "11.5"),
                Arrays.asList("11", "11", "45", "12.2"), Arrays.asList("12", "12", "46", "12.6"));

        // Verify size chart presence and content matching for each search result
        for (WebElement webElement : searchResults) {
            SearchResult result = new SearchResult(webElement);

            // Verify if the size chart exists for the search result
            if (result.verifySizeChartExists()) {
                logStatus("Step Success", "Successfully validated presence of Size Chart Link", "PASS");

                // Verify if size dropdown exists
                status = result.verifyExistenceofSizeDropdown(driver);
                logStatus("Step Success", "Validated presence of drop down", status ? "PASS" : "FAIL");

                // Open the size chart
                if (result.openSizechart()) {

                    Thread.sleep(500);

                    // Verify if the size chart contents matches the expected values
                    if (result.validateSizeChartContents(expectedTableHeaders, expectedTableBody, driver)) {
                        logStatus("Step Success", "Successfully validated contents of Size Chart Link", "PASS");
                    } else {
                        logStatus("Step Failure", "Failure while validating contents of Size Chart Link", "FAIL");
                        takeScreenshot(driver,"Test Case 4 step failure","screenshot");
                    }

                    // Close the size chart modal
                    status = result.closeSizeChart(driver);

                } else {
                    logStatus("TestCase 4", "Test Case Fail. Failure to open Size Chart", "FAIL");
                    takeScreenshot(driver,"Test Case 4 fail","screenshot");
                    return false;
                }

            } else {
                logStatus("TestCase 4", "Test Case Fail. Size Chart Link does not exist", "FAIL");
                takeScreenshot(driver,"Test Case 4 fail","screenshot");
                return false;
            }
        }
        logStatus("TestCase 4", "Test Case PASS. Validated Size Chart Details", "PASS");
        takeScreenshot(driver,"Test Case 4 end","screenshot");
        return status;
    }

    /*
     * Verify the complete flow of checking out and placing order for products is
     * working correctly
     */
    public static Boolean TestCase05(RemoteWebDriver driver) throws InterruptedException {
        Boolean status;
        takeScreenshot(driver,"Test Case 5 start","screenshot");
        logStatus("Start TestCase", "Test Case 5: Verify Happy Flow of buying products", "DONE");

        // Go to the Register page
        Register registration = new Register(driver);
        registration.navigateToRegisterPage();

        // Register a new user
        status = registration.registerUser("testUser", "abc@123", true);
        if (!status) {
            logStatus("TestCase 5", "Test Case Failure. Happy Flow Test Failed", "FAIL");
            takeScreenshot(driver,"Test Case 5 fail","screenshot");
            return false;
        }

        // Save the username of the newly registered user
        lastGeneratedUserName = registration.lastGeneratedUsername;

        // Go to the login page
        Login login = new Login(driver);
        login.navigateToLoginPage();

        // Login with the newly registered user's credentials
        status = login.PerformLogin(lastGeneratedUserName, "abc@123");
        if (!status) {
            logStatus("Step Failure", "User Perform Login Failed", status ? "PASS" : "FAIL");
            logStatus("End TestCase", "Test Case 5: Happy Flow Test Failed : ", status ? "PASS" : "FAIL");
            takeScreenshot(driver,"Test Case 5 fail","screenshot");
        }

        // Go to the home page
        Home homePage = new Home(driver);
        homePage.navigateToHome();

        // Find required products by searching and add them to the user's cart
        status = homePage.searchForProduct("Yonex");
        homePage.addProductToCart("YONEX Smash Badminton Racquet");
        status = homePage.searchForProduct("Tan");
        homePage.addProductToCart("Tan Leatherette Weekender Duffle");

        // Click on the checkout button
        homePage.clickCheckout();

        // Add a new address on the Checkout page and select it
        Checkout checkoutPage = new Checkout(driver);
        checkoutPage.addNewAddress("Addr line 1 addr Line 2 addr line 3");
        checkoutPage.selectAddress("Addr line 1 addr Line 2 addr line 3");

        // Place the order
        checkoutPage.placeOrder();
        // SLEEP_STMT_04: Wait for place order to succeed and navigate to Thanks page
        Thread.sleep(3000);

        // Check if placing order redirected to the Thansk page
        status = driver.getCurrentUrl().endsWith("/thanks");

        // Go to the home page
        homePage.navigateToHome();
        Thread.sleep(3000);

        // Log out the user
        homePage.PerformLogout();

        logStatus("End TestCase", "Test Case 5: Happy Flow Test Completed : ", status ? "PASS" : "FAIL");
        takeScreenshot(driver,"Test Case 1 end","screenshot");
        return status;
    }

    /*
     * Verify the quantity of items in cart can be updated
     */
    public static Boolean TestCase06(RemoteWebDriver driver) throws InterruptedException {
        Boolean status;
        takeScreenshot(driver,"Test Case 6 start","screenshot");
        logStatus("Start TestCase", "Test Case 6: Verify that cart can be edited", "DONE");
        Home homePage = new Home(driver);
        Register registration = new Register(driver);
        Login login = new Login(driver);

        // TODO: CRIO_TASK_MODULE_TEST_AUTOMATION - TEST CASE 06: MILESTONE 5

        // TODO: Register a new user
        registration.navigateToRegisterPage();
        status = registration.registerUser("testUser", "abc@123", true);
        logStatus("Test Step", "User Registration : ", status ? "PASS" : "FAIL");
        if (!status) {
            logStatus("Test Step", "Verify user Registration : ", status ? "PASS" : "FAIL");
            takeScreenshot(driver,"Test Case 6 step failure","screenshot");
            return false;
        }
        lastGeneratedUserName = registration.lastGeneratedUsername;

        // TODO: Login using the newly registed user
        login.navigateToLoginPage();
        status = login.PerformLogin(lastGeneratedUserName, "abc@123");
        logStatus("Test Step", "User Perform Login: ", status ? "PASS" : "FAIL");
        if (!status) {
            logStatus("Test Step" , "Verify user Registration : ", status ? "PASS" : "FAIL");
            takeScreenshot(driver,"Test Case 6 fail","screenshot");
            return false;
        }

        // TODO: Add "Xtend Smart Watch" to cart
        homePage.navigateToHome();
        status = homePage.searchForProduct("Watch");
        homePage.addProductToCart("Xtend Smart Watch");
        // Thread.sleep(500);

        // TODO: Add "Yarine Floor Lamp" to cart
        status = homePage.searchForProduct("Lamp");
        homePage.addProductToCart("Yarine Floor Lamp");
        // Thread.sleep(500);

        // update watch quantity to 2
        homePage.changeProductQuantityinCart("Xtend Smart Watch", 2);
        // Thread.sleep(500);

        // update table lamp quantity to 0
        homePage.changeProductQuantityinCart("Yarine Floor Lamp", 0);
        // Thread.sleep(500);

        // update watch quantity again to 1
        homePage.changeProductQuantityinCart("Xtend Smart Watch", 1);
        // Thread.sleep(500);

        homePage.clickCheckout();

        Checkout checkoutPage = new Checkout(driver);
        checkoutPage.addNewAddress("Addr line 1 addr Line 2 addr line 3");
        checkoutPage.selectAddress("Addr line 1 addr Line 2 addr line 3");
        // Thread.sleep(2000);

        checkoutPage.placeOrder();
        Thread.sleep(2000);

        status = driver.getCurrentUrl().endsWith("/thanks");

        homePage.navigateToHome();
        Thread.sleep(3000);
        homePage.PerformLogout();

        logStatus("End TestCase", "Test Case 6: Verify that cart can be edited: ", status ? "PASS" : "FAIL");
        takeScreenshot(driver,"Test Case 6 end","screenshot");
        return status;
    }

    /*
     * Verify that the cart contents are persisted after logout
     */
    public static Boolean TestCase07(RemoteWebDriver driver) throws InterruptedException {
        Boolean status = false;
        List<String> expectedResult = Arrays.asList("Stylecon 9 Seater RHS Sofa Set",
                "Xtend Smart Watch");

        takeScreenshot(driver,"Test Case 7 start","screenshot");
        logStatus("Start TestCase", "Test Case 7: Verify that cart contents are persisted after logout", "DONE");

        Register registration = new Register(driver);
        Login login = new Login(driver);
        Home homePage = new Home(driver);

        // TODO: CRIO_TASK_MODULE_TEST_AUTOMATION - TEST CASE 07: MILESTONE 6
        // TODO: Register a new user
        registration.navigateToRegisterPage();
        status = registration.registerUser("testUser", "abc@123", true);
        logStatus("Test Step", "User Registration : ", status ? "PASS" : "FAIL");
        if (!status) {
            logStatus("Test Step", "Verify user Registration : ", status ? "PASS" : "FAIL");
            takeScreenshot(driver,"Test Case 7 fail","screenshot");
            return false;
        }
        lastGeneratedUserName = registration.lastGeneratedUsername;

        // TODO: Login using the newly created user
        login.navigateToLoginPage();
        status = login.PerformLogin(lastGeneratedUserName, "abc@123");
        logStatus("Test Step", "User Perform Login: ", status ? "PASS" : "FAIL");
        if (!status) {
            logStatus("Test Step" , "Verify user Registration : ", status ? "PASS" : "FAIL");
            takeScreenshot(driver,"Test Case 7 fail","screenshot");
            return false;
        }

        homePage.navigateToHome();
        status = homePage.searchForProduct("Stylecon");
        homePage.addProductToCart("Stylecon 9 Seater RHS Sofa Set");

        status = homePage.searchForProduct("Xtend");
        homePage.addProductToCart("Xtend Smart Watch");

        homePage.PerformLogout();

        login.navigateToLoginPage();
        status = login.PerformLogin(lastGeneratedUserName, "abc@123");

        status = homePage.verifyCartContents(expectedResult);

        logStatus("End TestCase", "Test Case 7: Verify that cart contents are persisted after logout: ",
                status ? "PASS" : "FAIL");

        homePage.PerformLogout();
        takeScreenshot(driver,"Test Case 7 end","screenshot");
        return status;
    }

    public static Boolean TestCase08(RemoteWebDriver driver) throws InterruptedException {
        Boolean status;
        takeScreenshot(driver,"Test Case 8 start","screenshot");
        logStatus("Start TestCase",
                "Test Case 8: Verify that insufficient balance error is thrown when the wallet balance is not enough",
                "DONE");

        Register registration = new Register(driver);
        registration.navigateToRegisterPage();
        status = registration.registerUser("testUser", "abc@123", true);
        if (!status) {
            logStatus("Step Failure", "User Perform Registration Failed", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 8: Verify that insufficient balance error is thrown when the wallet balance is not enough: ",
                    status ? "PASS" : "FAIL");
            takeScreenshot(driver,"Test Case 8 fail","screenshot");
            return false;
        }
        lastGeneratedUserName = registration.lastGeneratedUsername;

        Login login = new Login(driver);
        login.navigateToLoginPage();
        status = login.PerformLogin(lastGeneratedUserName, "abc@123");
        if (!status) {
            logStatus("Step Failure", "User Perform Login Failed", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 8: Verify that insufficient balance error is thrown when the wallet balance is not enough: ",
                    status ? "PASS" : "FAIL");
        takeScreenshot(driver,"Test Case 8 fail","screenshot");
            return false;
        }

        Home homePage = new Home(driver);
        homePage.navigateToHome();
        status = homePage.searchForProduct("Stylecon");
        homePage.addProductToCart("Stylecon 9 Seater RHS Sofa Set");
        Thread.sleep(2000);

        homePage.changeProductQuantityinCart("Stylecon 9 Seater RHS Sofa Set", 10);

        homePage.clickCheckout();

        Checkout checkoutPage = new Checkout(driver);
        checkoutPage.addNewAddress("Addr line 1 addr Line 2 addr line 3");
        checkoutPage.selectAddress("Addr line 1 addr Line 2 addr line 3");

        checkoutPage.placeOrder();
        Thread.sleep(3000);

        status = checkoutPage.verifyInsufficientBalanceMessage();

        logStatus("End TestCase",
                "Test Case 8: Verify that insufficient balance error is thrown when the wallet balance is not enough: ",
                status ? "PASS" : "FAIL");

        takeScreenshot(driver,"Test Case 8 end","screenshot");
        
        return status;

    }

    public static Boolean TestCase09(RemoteWebDriver driver) throws InterruptedException {
        Boolean status = false;
        takeScreenshot(driver,"Test Case 8 start","screenshot");
        logStatus("Start TestCase",
                "Test Case 9: Verify that the products added to cart in one tab do get reflected in a new tab",
                "DONE");

        Register registration = new Register(driver);
        registration.navigateToRegisterPage();
        status = registration.registerUser("testUser", "abc@123", true);
        if (!status) {
            logStatus("Step Failure", "User Perform Registration Failed", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 9: Verify that the products added to cart in one tab do get reflected in a new tab: ",
                    status ? "PASS" : "FAIL");
            takeScreenshot(driver,"Test Case 9 fail","screenshot");
            return false;
        }
        lastGeneratedUserName = registration.lastGeneratedUsername;

        Login login = new Login(driver);
        login.navigateToLoginPage();
        status = login.PerformLogin(lastGeneratedUserName, "abc@123");
        if (!status) {
            logStatus("Step Failure", "User Perform Login Failed", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 9: Verify that the products added to cart in one tab do get reflected in a new tab: ",
                    status ? "PASS" : "FAIL");
        takeScreenshot(driver,"Test Case 9 fail","screenshot");
            return false;
        }

        Home homePage = new Home(driver);
        homePage.navigateToHome();
        status = homePage.searchForProduct("YONEX Smash Badminton Racquet");
        homePage.addProductToCart("YONEX Smash Badminton Racquet");

        String parentWindow = driver.getWindowHandle();

        JavascriptExecutor jscript = (JavascriptExecutor) driver;
        jscript.executeScript("window.open('https://crio-qkart-frontend-qa.vercel.app/');");

        Set<String> s = driver.getWindowHandles();
        
        for(String temp:s) {
            if(!temp.equals(parentWindow)) {
                driver.switchTo().window(temp);
                try {
					Thread.sleep(300);
				} catch (InterruptedException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
            }
        }

        homePage.navigateToHome();   
        Thread.sleep(2000);
        
        List<String> expectedResult = Arrays.asList("YONEX Smash Badminton Racquet");
        status = homePage.verifyCartContents(expectedResult);
        // TODO: CRIO_TASK_MODULE_SYNCHRONISATION -

        for (String temp : s) {
            // If not the main window, switch to it so that we can close it
            if (!temp.equals(parentWindow)) {
                    driver.switchTo().window(temp);
                    driver.close();
            }
        }

        logStatus("End TestCase",
                "Test Case 9: Verify that the products added to cart in one tab do get reflected in a new tab: ",
                status ? "PASS" : "FAIL");

        driver.switchTo().window(parentWindow);

        return status;
    }

    public static Boolean TestCase10(RemoteWebDriver driver) throws InterruptedException {
        // TODO: CRIO_TASK_MODULE_SYNCHRONISATION -
        Boolean status = false;

        logStatus("Start TestCase",
                "Test Case 10: Verifying whether the footer links are working properly or not",
                "DONE");

        Home homePage = new Home(driver);
        homePage.navigateToHome();
        String parentWindow = driver.getWindowHandle();

        WebElement privacyPolicy = driver.findElement(By.linkText("Privacy policy"));
        privacyPolicy.click();

        String privacyPage = "";
        Set<String> s = driver.getWindowHandles();

        for(String temp:s) {
			if(!temp.equals(parentWindow)) {
				privacyPage = temp;
                break;
			}
		}
        status = driver.getCurrentUrl().equals("https://crio-qkart-frontend-qa.vercel.app/");

        if(!status) {
            logStatus("Step Failure", "Not the same parent URL", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 10: Verifying whether the footer links are working properly or not: ",
                    status ? "PASS" : "FAIL");
        }

        logStatus("Step Success", "The same parent URL", status ? "PASS" : "FAIL");

        driver.switchTo().window(privacyPage);

        Thread.sleep(2000);
        status = driver.getCurrentUrl().endsWith("/privacy-policy");

        if(!status) {
            logStatus("Step Failure", "Privacy policy page not opened successfully", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 10: Verifying whether the footer links are working properly or notb: ",
                    status ? "PASS" : "FAIL");
        }

        logStatus("Step Success", "Privacy policy page opened successfully", status ? "PASS" : "FAIL");

        driver.switchTo().window(parentWindow);

        WebElement termsOfService = driver.findElement(By.linkText("Terms of Service"));
        termsOfService.click();

        String termsPage = "";
        Set<String> s1 = driver.getWindowHandles();

        for(String temp:s1) {
			if(!temp.equals(parentWindow) && !temp.equals(privacyPage)) {
				termsPage = temp;
                break;
			}
		}
        status = driver.getCurrentUrl().equals("https://crio-qkart-frontend-qa.vercel.app/");

        if(!status) {
            logStatus("Step Failure", "Not the same parent URL", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 10: Verifying whether the footer links are working properly or not: ",
                    status ? "PASS" : "FAIL");
        }

        logStatus("Step Success", "The same parent URL", status ? "PASS" : "FAIL");

        driver.switchTo().window(termsPage);
        status = driver.getCurrentUrl().endsWith("/terms-of-service");

        if(!status) {
            logStatus("Step Failure", "Terms of Service page not opened successfully", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 10: Verifying whether the footer links are working properly or notb: ",
                    status ? "PASS" : "FAIL");
        }

        logStatus("Step Success", "Terms of Service page opened successfully", status ? "PASS" : "FAIL");

        driver.switchTo().window(parentWindow);

        WebElement aboutUs = driver.findElement(By.linkText("About us"));
        aboutUs.click();

        String aboutPage = "";
        Set<String> s2 = driver.getWindowHandles();

        for(String temp:s2) {
			if(!temp.equals(parentWindow) && !temp.equals(privacyPage) && !temp.equals(termsPage)) {
				aboutPage = temp;
                break;
			}
		}
        status = driver.getCurrentUrl().equals("https://crio-qkart-frontend-qa.vercel.app/");

        if(!status) {
            logStatus("Step Failure", "Not the same parent URL", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 10: Verifying whether the footer links are working properly or not: ",
                    status ? "PASS" : "FAIL");
        }

        logStatus("Step Success", "The same parent URL", status ? "PASS" : "FAIL");

        driver.switchTo().window(aboutPage);
        status = driver.getCurrentUrl().endsWith("/aboutus");

        if(!status) {
            logStatus("Step Failure", "About Us page not opened successfully", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 10: Verifying whether the footer links are working properly or notb: ",
                    status ? "PASS" : "FAIL");
        }

        logStatus("Step Success", "About Us page opened successfully", status ? "PASS" : "FAIL");

        for (String temp : s2) {
            // If not the main window, switch to it so that we can close it
            if (!temp.equals(parentWindow)) {
                    driver.switchTo().window(temp);
                    Thread.sleep(2000);
                    driver.close();
            }
        }

        driver.switchTo().window(parentWindow);

        logStatus("End TestCase",
                "Test Case 10: Verifying whether the footer links are working properly or not: ",
                status ? "PASS" : "FAIL");

        return status;
    }

    public static Boolean TestCase11(RemoteWebDriver driver) throws InterruptedException {
        Boolean status = false;
        // TODO: CRIO_TASK_MODULE_SYNCHRONISATION -

        logStatus("Start TestCase",
                "Test Case 11: Verifying the working of 'Contact Us' link",
                "DONE");

        Home homePage = new Home(driver);
        homePage.navigateToHome();

        WebElement contactBtn = driver.findElement(By.xpath("//*[@id='root']/div/div/div[5]/div[2]/p[3]"));
        contactBtn.click();

        Thread.sleep(1000);

        WebElement name = driver.findElement(By.xpath("/html/body/div[2]/div[3]/div/section/div/div/div/form/div/div/div[2]/div[1]/div/input"));

        status = name.isDisplayed();
        if(!status) {
            logStatus("Step Failure", "Contact us form not opened", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 11: Verifying the working of 'Contact Us' link: ",
                    status ? "PASS" : "FAIL");
        }

        logStatus("Step Failure", "Contact us form opened", status ? "PASS" : "FAIL");

        name.sendKeys("crio user");

        WebElement email = driver.findElement(By.xpath("/html/body/div[2]/div[3]/div/section/div/div/div/form/div/div/div[2]/div[2]/div/input"));
        email.sendKeys("criouser@gmail.com");

        WebElement message = driver.findElement(By.xpath("/html/body/div[2]/div[3]/div/section/div/div/div/form/div/div/div[3]/input"));
        message.sendKeys("Testing the contact us page");

        WebElement submitBtn = driver.findElement(By.xpath("/html/body/div[2]/div[3]/div/section/div/div/div/form/div/div/div[4]/div/button"));
        submitBtn.click();

        logStatus("Step Success", "Contact us form closed", status ? "PASS" : "FAIL");

        logStatus("End TestCase",
        "Test Case 11: Verifying the working of 'Contact Us' link: ",
        status ? "PASS" : "FAIL");

        return status;
    }

    public static Boolean TestCase12(RemoteWebDriver driver) throws InterruptedException {
        // TODO: CRIO_TASK_MODULE_SYNCHRONISATION -
        Boolean status;
        logStatus("Start TestCase",
                "Test Case 12: Once the purchase is successful, verify if ads are displayed on the final page",
                "DONE");

        Register registration = new Register(driver);
        registration.navigateToRegisterPage();
        status = registration.registerUser("testUser", "abc@123", true);
        if (!status) {
            logStatus("Step Failure", "User Perform Registration Failed", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 12: Once the purchase is successful, verify if ads are displayed on the final page: ",
                    status ? "PASS" : "FAIL");
            return false;
        }
        lastGeneratedUserName = registration.lastGeneratedUsername;

        Login login = new Login(driver);
        login.navigateToLoginPage();
        status = login.PerformLogin(lastGeneratedUserName, "abc@123");
        if (!status) {
            logStatus("Step Failure", "User Perform Login Failed", status ? "PASS" : "FAIL");
            logStatus("End TestCase",
                    "Test Case 12: Once the purchase is successful, verify if ads are displayed on the final page: ",
                    status ? "PASS" : "FAIL");
            return false;
        }

        Home homePage = new Home(driver);
        homePage.navigateToHome();

        status = homePage.searchForProduct("YONEX Smash Badminton Racquet");
        homePage.addProductToCart("YONEX Smash Badminton Racquet");
        Thread.sleep(2000);

        homePage.clickCheckout();

        Checkout checkoutPage = new Checkout(driver);
        checkoutPage.addNewAddress("Addr line 4 addr Line 5 addr line 6");
        checkoutPage.selectAddress("Addr line 4 addr Line 5 addr line 6");

        // Place the order
        checkoutPage.placeOrder();
        Thread.sleep(1000);

        // Check if placing order redirected to the Thanks page
        status = driver.getCurrentUrl().endsWith("/thanks");

        try {
            String parentWindow = driver.getWindowHandle();

        WebElement frame1 = driver.findElement(By.xpath("//*[@id='root']/div/div[2]/iframe"));
        WebElement frame2 = driver.findElement(By.xpath("//*[@id='root']/div/div[2]/div/iframe[1]"));
        WebElement frame3 = driver.findElement(By.xpath("//*[@id='root']/div/div[2]/div/iframe[2]"));

        driver.switchTo().frame(frame1);
        driver.switchTo().parentFrame();

        driver.switchTo().frame(frame2);
        driver.findElement(By.xpath("/html/body/div/div/div/div/div/div/button[2]")).click();

        status = driver.getCurrentUrl().endsWith("/checkout");
        driver.navigate().back();

        driver.switchTo().parentFrame();

        frame3 = driver.findElement(By.xpath("//*[@id='root']/div/div[2]/div/iframe[2]"));

        driver.switchTo().frame(frame3);
        driver.findElement(By.xpath("/html/body/div/div/div/div/div/div/button[2]")).click();
        status = driver.getCurrentUrl().endsWith("/checkout");
        driver.navigate().back();
        driver.switchTo().parentFrame();
        return true;
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        int totalTests = 0;
        int passedTests = 0;
        Boolean status;
        RemoteWebDriver driver = createDriver();
        // Maximize and Implicit Wait for things to initailize
        driver.manage().window().maximize();
        driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);

        try {
            // Execute Test Case 1
            
            totalTests += 1;
            status = TestCase01(driver);
            if (status) {
                passedTests += 1;
            }

            System.out.println("");

            // // Execute Test Case 2
            totalTests += 1;
            status = TestCase02(driver);
            if (status) {
                passedTests += 1;
            }

            System.out.println("");

            // Execute Test Case 3
            totalTests += 1;
            status = TestCase03(driver);
            if (status) {
            passedTests += 1;
            }

            System.out.println("");

            // Execute Test Case 4
            totalTests += 1;
            status = TestCase04(driver);
            if (status) {
            passedTests += 1;
            }

            System.out.println("");

            // Execute Test Case 5
            totalTests += 1;
            status = TestCase05(driver);
            if (status) {
            passedTests += 1;
            }

            System.out.println("");

            // Execute Test Case 6
            totalTests += 1;
            status = TestCase06(driver);
            if (status) {
            passedTests += 1;
            }

            System.out.println("");

            // Execute Test Case 7
            totalTests += 1;
            status = TestCase07(driver);
            if (status) {
            passedTests += 1;
            }

            System.out.println("");

            // Execute Test Case 8
            totalTests += 1;
            status = TestCase08(driver);
            if (status) {
            passedTests += 1;
            }

            System.out.println("");

            // Execute Test Case 9
            totalTests += 1;
            status = TestCase09(driver);
            if (status) {
            passedTests += 1;
            }

            System.out.println("");

            // Execute Test Case 10
            totalTests += 1;
            status = TestCase10(driver);
            if (status) {
            passedTests += 1;
            }

            System.out.println("");

            // Execute Test Case 11
            totalTests += 1;
            status = TestCase11(driver);
            if (status) {
            passedTests += 1;
            }

            System.out.println("");

            // Execute Test Case 12
            totalTests += 1;
            status = TestCase12(driver);
            if (status) {
            passedTests += 1;
            }

            System.out.println("");

        } catch (Exception e) {
            throw e;
        } finally {
            // quit Chrome Driver
            driver.quit();

            System.out.println(String.format("%s out of %s test cases Passed ", Integer.toString(passedTests),
                    Integer.toString(totalTests)));
        }
    }
}